#pragma once
// ValueTree identifiers for the project model. Property names are the ChopPreset JSON keys (unchanged — the
// tree serialises straight to the project file, see ProjectModel.h). Node types are capitalised.
#include <juce_core/juce_core.h>

namespace terminator::model::ids
{
#define TERMINATOR_ID(name) inline const juce::Identifier name(#name);
// node types
TERMINATOR_ID(Project)
TERMINATOR_ID(Chops)
TERMINATOR_ID(Chop)
TERMINATOR_ID(Pads)
TERMINATOR_ID(Pad)
TERMINATOR_ID(PadSources) // JSON padBufferMeta
TERMINATOR_ID(PadSource)
TERMINATOR_ID(SourceRoutes)
TERMINATOR_ID(PadRoutes)
TERMINATOR_ID(PadGroups)
TERMINATOR_ID(PadChoke)
TERMINATOR_ID(SourceNorm)
TERMINATOR_ID(Entry) // generic key/value map node
TERMINATOR_ID(SourceFx)
TERMINATOR_ID(Fx)
TERMINATOR_ID(Sequences)
TERMINATOR_ID(Sequence)
TERMINATOR_ID(Master)
TERMINATOR_ID(ExtraFX)
TERMINATOR_ID(Trims)
TERMINATOR_ID(Trim)
TERMINATOR_ID(TrimChop)
TERMINATOR_ID(Stems)
TERMINATOR_ID(SourceStems)
TERMINATOR_ID(SourceStem)
TERMINATOR_ID(StemAssets)
// properties (JSON keys)
TERMINATOR_ID(videoId)
TERMINATOR_ID(savedAt)
TERMINATOR_ID(name)
TERMINATOR_ID(trackTitle)
TERMINATOR_ID(bpm)
TERMINATOR_ID(nextChopId)
TERMINATOR_ID(timeline)
TERMINATOR_ID(timelineLength)
TERMINATOR_ID(seqBars)
TERMINATOR_ID(seqResolution)
TERMINATOR_ID(seqGrid)
TERMINATOR_ID(seqLoop)
TERMINATOR_ID(currentSeqIdx)
TERMINATOR_ID(normalize)
TERMINATOR_ID(normalizeGain)
TERMINATOR_ID(masterClip)
TERMINATOR_ID(stretchEnabled)
TERMINATOR_ID(targetBpm)
TERMINATOR_ID(chopOffsetMs)
TERMINATOR_ID(reverseSample)
TERMINATOR_ID(chopVolume)
TERMINATOR_ID(metronomeBpm)
TERMINATOR_ID(inputQuantize)
TERMINATOR_ID(nextSampleTrack)
TERMINATOR_ID(nextChokeGroup)
TERMINATOR_ID(drums)
TERMINATOR_ID(bass)
TERMINATOR_ID(mixer)
TERMINATOR_ID(assets)
TERMINATOR_ID(version)
TERMINATOR_ID(id)
TERMINATOR_ID(start)
TERMINATOR_ID(end)
TERMINATOR_ID(free)
TERMINATOR_ID(index)
TERMINATOR_ID(chopId)
TERMINATOR_ID(mode)
TERMINATOR_ID(pitch)
TERMINATOR_ID(gate)
TERMINATOR_ID(fadeIn)
TERMINATOR_ID(fadeOut)
TERMINATOR_ID(stems)
TERMINATOR_ID(reverse)
TERMINATOR_ID(pad)
TERMINATOR_ID(title)
TERMINATOR_ID(key)
TERMINATOR_ID(value)
TERMINATOR_ID(attack)
TERMINATOR_ID(fine)
TERMINATOR_ID(bars)
TERMINATOR_ID(resolution)
TERMINATOR_ID(viewResolution)
TERMINATOR_ID(grid)
TERMINATOR_ID(revGrid)
TERMINATOR_ID(velGrid)
TERMINATOR_ID(loop)
TERMINATOR_ID(startSec)
TERMINATOR_ID(endSec)
TERMINATOR_ID(padIdx)
TERMINATOR_ID(quality)
TERMINATOR_ID(readyRanges)
// master
TERMINATOR_ID(volume)
TERMINATOR_ID(filterFreq)
TERMINATOR_ID(filterEnabled)
TERMINATOR_ID(eqLow)
TERMINATOR_ID(eqMid)
TERMINATOR_ID(eqHigh)
TERMINATOR_ID(compStyle)
TERMINATOR_ID(compMix)
TERMINATOR_ID(delayTime)
TERMINATOR_ID(delayFeedback)
TERMINATOR_ID(delayMix)
TERMINATOR_ID(reverbMix)
TERMINATOR_ID(reverbDecay)
TERMINATOR_ID(release)
#undef TERMINATOR_ID
} // namespace terminator::model::ids
